baseURL = 'https://notes.github.io/'
languageCode = 'en-us'
title = 'Environment Setup'
theme = 'hugo-book'

[params]
    # (Optional, default light) Sets color theme: light, dark or auto.
    # Theme 'auto' switches between dark and light modes based on browser/os preferences
    BookTheme = 'auto'
